# Generated by Django 6.0.3 on 2026-05-15 16:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compra', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^(\\d{12}|\\d+/\\d{4})$', 'Formato deve ser 12 dígitos ou n/yyyy')], verbose_name='Número de compra')),
                ('numero_sei', models.CharField(blank=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{8}/\\d{4}-\\d{2}$', 'Formato deve ser 154.00009999/2026-99')], verbose_name='Número SEI')),
                ('objeto', models.CharField(blank=True, max_length=255, verbose_name='Objeto')),
                ('modalidade', models.CharField(blank=True, choices=[('Audiência Pública', 'Audiência Pública'), ('Concorrência', 'Concorrência'), ('Concurso', 'Concurso'), ('Credenciamento', 'Credenciamento'), ('Dispensa', 'Dispensa'), ('Inexigibilidade', 'Inexigibilidade'), ('Leilão', 'Leilão'), ('Manifestação de interesse', 'Manifestação de interesse'), ('Pré-Qualificação', 'Pré-Qualificação'), ('Pregão', 'Pregão'), ('Registro de Preços', 'Registro de Preços')], max_length=255, verbose_name='Modalidade')),
                ('tipo', models.CharField(blank=True, choices=[('FORNECIMENTO', 'FORNECIMENTO'), ('SERVIÇO', 'SERVIÇO')], max_length=20, verbose_name='Tipo')),
                ('valor_total_previsto', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor total previsto')),
                ('nome_agente_contratacao', models.CharField(blank=True, choices=[('Lucas', 'Lucas'), ('Marcos', 'Marcos'), ('Melina', 'Melina'), ('Regina', 'Regina')], max_length=255, verbose_name='Agente de contratação')),
                ('disputa', models.BooleanField(default=True, verbose_name='Disputa')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='compras/', verbose_name='Arquivo PDF')),
                ('data_estimativa_orcamento', models.DateField(blank=True, null=True, verbose_name='Data da proposta comercial')),
                ('data_proposta_comercial', models.DateField(blank=True, null=True, verbose_name='Data da proposta comercial')),
                ('numero_comprasgov', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^(\\d{12}|\\d+/\\d{4})$', 'Formato deve ser 12 dígitos ou n/yyyy')], verbose_name='Número comprasgov')),
                ('valor_efetivo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor efetivo')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('is_propria_instituicao', models.BooleanField(default=False, verbose_name='É a própria instituição')),
            ],
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demanda', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^(\\d{12}|\\d+/\\d{4})$', 'Formato deve ser 12 dígitos ou n/yyyy')], verbose_name='Número da demanda')),
                ('centro_gerencial', models.CharField(blank=True, max_length=50, verbose_name='Centro Gerencial')),
                ('grupo_orcamentario', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d{2}\\.\\d{3}$', 'Formato deve ser 59.001')], verbose_name='Grupo orçamentário')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas', to='compras.compra')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordem', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='Ordem')),
                ('codigo_material', models.CharField(blank=True, max_length=14, null=True, verbose_name='Código material')),
                ('codigo_comprasgov', models.CharField(blank=True, max_length=14, null=True, verbose_name='Código compras gov')),
                ('codigo_contabiliza', models.CharField(blank=True, max_length=14, null=True, verbose_name='Código contabiliza')),
                ('codigo_bem', models.CharField(blank=True, max_length=14, null=True, verbose_name='Código bem compras gov')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('item_despesa', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'Deve ser apenas números')], verbose_name='Item de despesa')),
                ('valor_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor médio')),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade')),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.demanda')),
            ],
            options={
                'ordering': ['demanda', 'numero_ordem'],
                'unique_together': {('demanda', 'numero_ordem')},
            },
        ),
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornecedor', models.CharField(max_length=255, verbose_name='Nome do fornecedor')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor unitário')),
                ('codigo_contabiliza', models.CharField(blank=True, max_length=14, verbose_name='Código contabiliza')),
                ('codigo_bem', models.CharField(blank=True, max_length=14, verbose_name='Código bem compras gov')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisas', to='compras.compra')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesquisas', to='compras.item')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Número do contrato')),
                ('modalidade_garantia', models.CharField(blank=True, choices=[('CAUCAO_DINHEIRO', 'Caução em dinheiro'), ('CAUCAO_TITULOS', 'Caução em títulos públicos'), ('SEGURO_GARANTIA', 'Seguro-garantia'), ('FIANCA_BANCARIA', 'Fiança bancária'), ('TITULO_CAPITALIZACAO', 'Título de capitalização')], max_length=30, null=True, verbose_name='Modalidade de garantia')),
                ('valor_garantia', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor da garantia')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data do contrato')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='compras.compra')),
            ],
        ),
        migrations.CreateModel(
            name='RepresentanteContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255, verbose_name='Cargo')),
                ('responsavel_assinatura', models.BooleanField(default=True, verbose_name='Responsável pela assinatura')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representantes', to='compras.contrato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representantes_contratos', to='compras.pessoajuridica')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_representados', to='compras.pessoafisica')),
            ],
        ),
    ]
