# Generated by Django 6.0.3 on 2026-04-13 13:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compra', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d+/\\d{4}$', 'Formato deve ser n/yyyy')], verbose_name='Número de compra')),
                ('numero_sei', models.CharField(blank=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{8}/\\d{4}-\\d{2}$', 'Formato deve ser 154.00009999/2026-99')], verbose_name='Número SEI')),
                ('objeto', models.CharField(blank=True, max_length=255, verbose_name='Objeto')),
                ('modalidade', models.CharField(blank=True, choices=[('COMPRA DIRETA COM DISPUTA', 'COMPRA DIRETA COM DISPUTA'), ('COMPRA DIRETA SEM DISPUTA', 'COMPRA DIRETA SEM DISPUTA'), ('PREGÃO', 'PREGÃO'), ('INEXIGIBILIADE', 'INEXIGIBILIADE'), ('CONCURSO', 'CONCURSO')], max_length=30, verbose_name='Modalidade')),
                ('tipo', models.CharField(blank=True, choices=[('FORNECIMENTO', 'FORNECIMENTO'), ('SERVIÇO', 'SERVIÇO')], max_length=20, verbose_name='Tipo')),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor estimado')),
                ('nome_agente_contratacao', models.CharField(blank=True, choices=[('Lucas', 'Lucas'), ('Marcos', 'Marcos'), ('Melina', 'Melina'), ('Regina', 'Regina')], max_length=255, verbose_name='Agente de contratação')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='compras/', verbose_name='Arquivo PDF')),
            ],
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demanda', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d+/\\d{4}$', 'Formato deve ser n/yyyy')], verbose_name='Número da demanda')),
                ('centro_gerencial', models.CharField(blank=True, max_length=50, verbose_name='Centro Gerencial')),
                ('grupo_orcamentario', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d{2}\\.\\d{3}$', 'Formato deve ser 59.001')], verbose_name='Grupo orçamentário')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas', to='compras.compra')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ordem', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='Ordem')),
                ('codigo_material', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator('^\\d{7,14}$', 'Formato deve ter de 7 a 14 dígitos')], verbose_name='Código material')),
                ('codigo_compras_gov', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator('^\\d{7,14}$', 'Formato deve ter de 7 a 14 dígitos')], verbose_name='Código compras gov')),
                ('codigo_contabiliza', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator('^\\d{7,14}$', 'Formato deve ter de 7 a 14 dígitos')], verbose_name='Código contabiliza')),
                ('codigo_bem', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator('^\\d{7,14}$', 'Formato deve ter de 7 a 14 dígitos')], verbose_name='Código bem')),

                
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
                ('item_despesa', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator('^\\d+$', 'Deve ser apenas números')], verbose_name='Item de despesa')),
                ('valor_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor médio')),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.demanda')),
            ],
            options={
                'ordering': ['demanda', 'numero_ordem'],
                'unique_together': {('demanda', 'numero_ordem')},
            },
        ),
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornecedor', models.CharField(max_length=255, verbose_name='Nome do fornecedor')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor unitário')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisas', to='compras.compra')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisas', to='compras.item', null=True,
    blank=True)),
            ],
        ),
    ]
