# Generated by Django 6.0.3 on 2026-05-15 16:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('is_propria_instituicao', models.BooleanField(default=False, verbose_name='É a própria instituição')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='data_estimativa_orcamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data da proposta comercial'),
        ),
        migrations.AddField(
            model_name='compra',
            name='data_proposta_comercial',
            field=models.DateField(blank=True, null=True, verbose_name='Data da proposta comercial'),
        ),
        migrations.AddField(
            model_name='compra',
            name='numero_comprasgov',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^(\\d{12}|\\d+/\\d{4})$', 'Formato deve ser 12 dígitos ou n/yyyy')], verbose_name='Número comprasgov'),
        ),
        migrations.AddField(
            model_name='compra',
            name='valor_efetivo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor efetivo'),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, verbose_name='Número do contrato')),
                ('modalidade_garantia', models.CharField(blank=True, choices=[('CAUCAO_DINHEIRO', 'Caução em dinheiro'), ('CAUCAO_TITULOS', 'Caução em títulos públicos'), ('SEGURO_GARANTIA', 'Seguro-garantia'), ('FIANCA_BANCARIA', 'Fiança bancária'), ('TITULO_CAPITALIZACAO', 'Título de capitalização')], max_length=30, null=True, verbose_name='Modalidade de garantia')),
                ('valor_garantia', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor da garantia')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data do contrato')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='compras.compra')),
            ],
        ),
        migrations.CreateModel(
            name='RepresentanteContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255, verbose_name='Cargo')),
                ('responsavel_assinatura', models.BooleanField(default=True, verbose_name='Responsável pela assinatura')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representantes', to='compras.contrato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representantes_contratos', to='compras.pessoajuridica')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_representados', to='compras.pessoafisica')),
            ],
        ),
    ]
