# Generated by Django 6.0.3 on 2026-04-13 18:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='codigo_bem',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator('^\\d{7,14}$', 'Formato deve ter de 7 a 14 dígitos')], verbose_name='Código bem compras gov'),
        ),
    ]
