# Generated by Django 6.0.3 on 2026-05-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='modalidade_garantia',
            field=models.CharField(blank=True, choices=[('CAUCAO_DINHEIRO', 'Caução em dinheiro'), ('CAUCAO_TITULOS', 'Caução em títulos públicos'), ('SEGURO_GARANTIA', 'Seguro-garantia'), ('FIANCA_BANCARIA', 'Fiança bancária'), ('TITULO_CAPITALIZACAO', 'Título de capitalização')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='numero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_garantia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
