# Generated by Django 6.0.3 on 2026-05-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_contrato_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='codigo_bem',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Código bem compras gov'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='codigo_contabiliza',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Código contabiliza'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição'),
        ),
    ]
