# Generated by Django 6.0.3 on 2026-04-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_alter_item_codigo_bem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='codigo_bem',
            field=models.CharField(blank=True, max_length=14, verbose_name='Código bem compras gov'),
        ),
        migrations.AlterField(
            model_name='item',
            name='codigo_compras_gov',
            field=models.CharField(blank=True, max_length=14, verbose_name='Código compras gov'),
        ),
        migrations.AlterField(
            model_name='item',
            name='codigo_contabiliza',
            field=models.CharField(blank=True, max_length=14, verbose_name='Código contabiliza'),
        ),
        migrations.AlterField(
            model_name='item',
            name='codigo_material',
            field=models.CharField(blank=True, max_length=14, verbose_name='Código material'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='codigo_bem',
            field=models.CharField(blank=True, max_length=14, verbose_name='Código bem compras gov'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='codigo_contabiliza',
            field=models.CharField(blank=True, max_length=14, verbose_name='Código contabiliza'),
        ),
    ]
