# Generated by Django 6.0.3 on 2026-05-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_pesquisa_codigo_bem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unidade_medida',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidade de medida'),
        ),
    ]
