# Generated by Django 6.0.3 on 2026-04-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_item_codigo_bem_alter_item_codigo_compras_gov_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição'),
        ),
    ]
