# Generated by Django 6.0.3 on 2026-06-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_item_unidade_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='porcentual_garantia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentual de garantia'),
        ),
    ]
