# Generated by Django 6.0.3 on 2026-04-29 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_pesquisa_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='numero_compra',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^(\\d{12}|\\d+/\\d{4})$', 'Formato deve ser 12 dígitos ou n/yyyy')], verbose_name='Número de compra'),
        ),
    ]
