# Generated by Django 6.0.3 on 2026-04-06 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_alter_compra_modalidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.CharField(max_length=255, verbose_name='Nome do fornecedor')),
                ('quantidade', models.CharField(blank=True, max_length=50, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor unitário')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='compras.compra')),
            ],
        ),
    ]
