# Generated by Django 6.0.3 on 2026-06-08 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_remove_pessoafisica_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número da NE')),
                ('data_empenho', models.DateField(blank=True, null=True, verbose_name='Data do Empenho')),
                ('dotacao', models.CharField(blank=True, max_length=20, null=True, verbose_name='Dotação')),
                ('grupo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Grupo')),
                ('unidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Unidade')),
                ('fonte_recurso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonte de Recurso')),
                ('funcional_programatica', models.CharField(blank=True, max_length=255, null=True, verbose_name='Funcional Programática')),
                ('categoria_economica', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria Econômica')),
                ('grupo_despesa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Grupo de Despesa')),
                ('modalidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modalidade')),
                ('elemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Elemento')),
                ('item', models.CharField(blank=True, max_length=100, null=True, verbose_name='Item')),
                ('contrato', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empenho', to='compras.contrato')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empenhos', to='compras.organizacao')),
            ],
        ),
    ]
