# Generated by Django 6.0.3 on 2026-04-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_alter_compra_numero_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='modalidade',
            field=models.CharField(blank=True, max_length=255, verbose_name='Modalidade'),
        ),
    ]
