# Generated by Django 6.0.3 on 2026-04-10 17:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_cotacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['demanda', 'numero_ordem']},
        ),
        migrations.RemoveField(
            model_name='compra',
            name='valor',
        ),
        migrations.AddField(
            model_name='compra',
            name='valor_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor estimado'),
        ),
        migrations.AddField(
            model_name='item',
            name='codigo_bem',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'Formato deve ser 9999999')], verbose_name='Código bem compras gov'),
        ),
        migrations.AddField(
            model_name='item',
            name='codigo_contabiliza',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'Formato deve ser 9999999')], verbose_name='Código contabiliza'),
        ),
        migrations.AddField(
            model_name='item',
            name='numero_ordem',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='Ordem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='valor_medio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor médio'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='nome_agente_contratacao',
            field=models.CharField(blank=True, choices=[('Lucas', 'Lucas'), ('Marcos', 'Marcos'), ('Melina', 'Melina'), ('Regina', 'Regina')], max_length=255, verbose_name='Agente de contratação'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='numero_compra',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d+/\\d{4}$', 'Formato deve ser n/yyyy')], verbose_name='Número de compra'),
        ),
        migrations.AlterField(
            model_name='item',
            name='codigo_compras_gov',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'Formato deve ser 9999999')], verbose_name='Código compras gov'),
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demanda', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d+/\\d{4}$', 'Formato deve ser n/yyyy')], verbose_name='Número da demanda')),
                ('centro_despesa', models.CharField(blank=True, max_length=50, verbose_name='Centro de despesa')),
                ('grupo_orcamentario', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d{2}\\.\\d{3}$', 'Formato deve ser 59.001')], verbose_name='Grupo orçamentário')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas', to='compras.compra')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='item',
            name='demanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.demanda'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('demanda', 'numero_ordem')},
        ),
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornecedor', models.CharField(max_length=255, verbose_name='Nome do fornecedor')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor unitário')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisas', to='compras.item')),
            ],
        ),
        migrations.DeleteModel(
            name='Cotacao',
        ),
        migrations.RemoveField(
            model_name='item',
            name='centro_despesa',
        ),
        migrations.RemoveField(
            model_name='item',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='item',
            name='grupo_orcamentario',
        ),
        migrations.RemoveField(
            model_name='item',
            name='ordem',
        ),
    ]
