# Generated by Django 6.0.5 on 2026-06-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_empenho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unidade_medida',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unidade de medida'),
        ),
    ]
