# Generated by Django 6.0.3 on 2026-06-16 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_alter_item_unidade_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='representante_contratada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='compras.vinculoorganizacao', verbose_name='Representante Legal da Contratada'),
        ),
    ]
