# Generated by Django 6.0.3 on 2026-05-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_alter_demanda_numero_demanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='disputa',
            field=models.BooleanField(default=True, verbose_name='Disputa'),
        ),
    ]
