# Generated by Django 6.0.5 on 2026-06-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_contrato_representante_contratada'),
    ]

    operations = [
        migrations.AddField(
            model_name='empenho',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
