# Generated by Django 6.0.3 on 2026-05-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_compra_disputa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='modalidade',
            field=models.CharField(blank=True, choices=[('Audiência Pública', 'Audiência Pública'), ('Concorrência', 'Concorrência'), ('Concurso', 'Concurso'), ('Credenciamento', 'Credenciamento'), ('Dispensa', 'Dispensa'), ('Inexigibilidade', 'Inexigibilidade'), ('Leilão', 'Leilão'), ('Manifestação de interesse', 'Manifestação de interesse'), ('Pré-Qualificação', 'Pré-Qualificação'), ('Pregão', 'Pregão'), ('Registro de Preços', 'Registro de Preços')], max_length=255, verbose_name='Modalidade'),
        ),
    ]
