# Generated by Django 6.0.3 on 2026-06-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_empenho_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empenho',
            name='numero',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número da NE'),
        ),
    ]
