# Generated by Django 6.0.5 on 2026-06-18 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_alter_empenho_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='empenho',
            name='compra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empenho', to='compras.compra'),
        ),
        migrations.AlterModelTable(
            name='compra',
            table='compra',
        ),
        migrations.AlterModelTable(
            name='contrato',
            table='contrato',
        ),
        migrations.AlterModelTable(
            name='demanda',
            table='demanda',
        ),
        migrations.AlterModelTable(
            name='empenho',
            table='empenho',
        ),
        migrations.AlterModelTable(
            name='item',
            table='item',
        ),
        migrations.AlterModelTable(
            name='organizacao',
            table='organizacao',
        ),
        migrations.AlterModelTable(
            name='pesquisa',
            table='pesquisa',
        ),
        migrations.AlterModelTable(
            name='pessoafisica',
            table='pessoa_fisica',
        ),
        migrations.AlterModelTable(
            name='vinculoorganizacao',
            table='vinculo_organizacao',
        ),
    ]
