# Generated by Django 6.0.5 on 2026-06-18 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_empenho_compra_alter_compra_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empenho',
            name='compra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empenho', to='compras.compra'),
        ),
        migrations.AlterField(
            model_name='empenho',
            name='contrato',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empenho', to='compras.contrato'),
        ),
    ]
