# Generated by Django 6.0.5 on 2026-06-18 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0013_alter_empenho_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empenho',
            name='compra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empenho', to='compras.compra'),
        ),
    ]
