# Generated by Django 6.0.5 on 2026-06-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0014_alter_empenho_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinculoorganizacao',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='vinculoorganizacao',
            name='responsavel_assinatura',
        ),
    ]
