# Generated by Django 6.0.5 on 2026-07-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0018_alter_modelodocumento_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelodocumento',
            name='categoria',
            field=models.CharField(choices=[('PRINCIPAL', 'Documento Principal'), ('TR', 'Termo de Referência'), ('CONTRATO', 'Contrato'), ('CONFERENCIA', 'Conferência')], max_length=20, verbose_name='Categoria'),
        ),
    ]
