# Generated by Django 6.0.3 on 2026-04-02 18:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compra', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{6}/\\d{4}$', 'Formato deve ser 999999/2026')], verbose_name='Número de compra')),
                ('numero_sei', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{8}/\\d{4}-\\d{2}$', 'Formato deve ser 154.00009999/2026-99')], verbose_name='Número SEI')),
                ('objeto', models.CharField(max_length=255, verbose_name='Objeto')),
                ('modalidade', models.CharField(choices=[('COMPRA DIRETA COM DISPUTA', 'COMPRA DIRETA COM DISPUTA'), ('COMPRA DIRETA SEM DISPUTA', 'COMPRA DIRETA SEM DISPUTA'), ('PREGÃO', 'PREGÃO'), ('INEXIGIBILIADE', 'INEXIGIBILIADE'), ('CONCURSO', 'CONCURSO')], max_length=30, verbose_name='Modalidade')),
                ('tipo', models.CharField(choices=[('FORNECIMENTO', 'FORNECIMENTO'), ('SERVIÇO', 'SERVIÇO')], max_length=20, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('nome_agente_contratacao', models.CharField(choices=[('Vanessa', 'Vanessa'), ('Marcos', 'Marcos'), ('Regina', 'Regina'), ('Melina', 'Melina'), ('Lucas', 'Lucas')], max_length=255, verbose_name='Agente de contratação')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demanda', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{6}/\\d{4}$', 'Formato deve ser 999999/2026')], verbose_name='Demanda')),
                ('centro_despesa', models.CharField(max_length=50, verbose_name='Centro de despesa')),
                ('grupo_orcamentario', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{2}\\.\\d{3}$', 'Formato deve ser 59.001')], verbose_name='Grupo orçamentário')),
                ('codigo_compras_gov', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{7}$', 'Formato deve ser 9999999')], verbose_name='Código compras gov')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('item_despesa', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', 'Deve ser apenas números')], verbose_name='Item de despesa')),
                ('ordem', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='Ordem')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='compras.compra')),
            ],
            options={
                'ordering': ['compra', 'ordem'],
                'unique_together': {('compra', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fornecedor', models.CharField(max_length=255, verbose_name='Nome do fornecedor')),
                ('valor_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor unitário')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisas', to='compras.item')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisas', to='compras.compra')),
            ],
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_demanda', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d+/\\d{4}$', 'Formato deve ser n/yyyy')], verbose_name='Número da demanda')),
                ('centro_despesa', models.CharField(blank=True, max_length=50, verbose_name='Centro de despesa')),
                ('grupo_orcamentario', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d{2}\\.\\d{3}$', 'Formato deve ser 59.001')], verbose_name='Grupo orçamentário')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandas', to='compras.compra')),
            ],
        ),
    ]
