# Generated by Django 6.0.3 on 2026-04-06 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='compras/', verbose_name='Arquivo PDF'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='nome_agente_contratacao',
            field=models.CharField(choices=[('Lucas', 'Lucas'), ('Marcos', 'Marcos'), ('Melina', 'Melina'), ('Regina', 'Regina'), ('Vanessa', 'Vanessa')], max_length=255, verbose_name='Agente de contratação'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='numero_compra',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d+/\\d{4}$', 'Formato deve ser n/yyyy')], verbose_name='Número de compra'),
        ),
        migrations.AlterField(
            model_name='item',
            name='demanda',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d+/\\d{4}$', 'Formato deve ser n/YYYY')], verbose_name='Demanda'),
        ),
    ]
