# Generated by Django 6.0.3 on 2026-04-06 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compra_pdf_file_alter_compra_nome_agente_contratacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='centro_gerencial',
            field=models.CharField(blank=True, max_length=50, verbose_name='Centro Gerencial'),
        ),
        migrations.AlterField(
            model_name='item',
            name='codigo_compras_gov',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('^\\d{7}$', 'Formato deve ser 9999999')], verbose_name='Código compras gov'),
        ),
        migrations.AlterField(
            model_name='item',
            name='demanda',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator('^\\d+/\\d{4}$', 'Formato deve ser n/YYYY')], verbose_name='Demanda'),
        ),
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='item',
            name='grupo_orcamentario',
            field=models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator('^\\d{2}\\.\\d{3}$', 'Formato deve ser 59.001')], verbose_name='Grupo orçamentário'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_despesa',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d+$', 'Deve ser apenas números')], verbose_name='Item de despesa'),
        ),
    ]
