# Generated by Django 6.0.3 on 2026-04-06 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_item_centro_despesa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='modalidade',
            field=models.CharField(blank=True, choices=[('COMPRA DIRETA COM DISPUTA', 'COMPRA DIRETA COM DISPUTA'), ('COMPRA DIRETA SEM DISPUTA', 'COMPRA DIRETA SEM DISPUTA'), ('PREGÃO', 'PREGÃO'), ('INEXIGIBILIADE', 'INEXIGIBILIADE'), ('CONCURSO', 'CONCURSO')], max_length=30, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='nome_agente_contratacao',
            field=models.CharField(blank=True, choices=[('Lucas', 'Lucas'), ('Marcos', 'Marcos'), ('Melina', 'Melina'), ('Regina', 'Regina'), ('Vanessa', 'Vanessa')], max_length=255, verbose_name='Agente de contratação'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='numero_sei',
            field=models.CharField(blank=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{8}/\\d{4}-\\d{2}$', 'Formato deve ser 154.00009999/2026-99')], verbose_name='Número SEI'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='objeto',
            field=models.CharField(blank=True, max_length=255, verbose_name='Objeto'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='tipo',
            field=models.CharField(blank=True, choices=[('FORNECIMENTO', 'FORNECIMENTO'), ('SERVIÇO', 'SERVIÇO')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor'),
        ),
    ]
