# Generated by Django 6.0.3 on 2026-04-10 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_alter_item_options_remove_compra_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='codigo_bem',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator('^\\d{7}$', 'Formato deve ser 9999999')], verbose_name='Código bem compras gov'),
        ),
        migrations.AlterField(
            model_name='item',
            name='codigo_compras_gov',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator('^\\d{7}$', 'Formato deve ser 9999999')], verbose_name='Código compras gov'),
        ),
        migrations.AlterField(
            model_name='item',
            name='codigo_contabiliza',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator('^\\d{7}$', 'Formato deve ser 9999999')], verbose_name='Código contabiliza'),
        ),
    ]
